version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
  pre_build:
    commands:
      - echo Pre-build started on `date`
      - cd frontend
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - mkdir -p ~/.ssh
      - aws s3 cp s3://mac-terraform-state-001/backend_pipeline-key_pair.pem ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@34.207.115.20 "sudo chown ubuntu:ubuntu /var/www/html"
      - echo Copying files to server...
      - scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r build/* ubuntu@34.207.115.20:/var/www/html/
